// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSgN4YOmHZ3Ar6NrzWf8fE5mQETqYom10',
    appId: '1:525884237680:web:020fcc0808e24b0dfb11b5',
    messagingSenderId: '525884237680',
    projectId: 'tuankiet-27c37',
    authDomain: 'tuankiet-27c37.firebaseapp.com',
    storageBucket: 'tuankiet-27c37.appspot.com',
    measurementId: 'G-PSPBQP8LN5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnoOME4xm38QgRZ-x8P_WXoA_2xp88S3Y',
    appId: '1:525884237680:android:9e95ac959460e13bfb11b5',
    messagingSenderId: '525884237680',
    projectId: 'tuankiet-27c37',
    storageBucket: 'tuankiet-27c37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZtDKL2FYceMQGlj2Rsjm9Xb5XSOTxY40',
    appId: '1:525884237680:ios:9acc09eade1b32d1fb11b5',
    messagingSenderId: '525884237680',
    projectId: 'tuankiet-27c37',
    storageBucket: 'tuankiet-27c37.appspot.com',
    iosBundleId: 'com.example.shopsmartAdminAr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZtDKL2FYceMQGlj2Rsjm9Xb5XSOTxY40',
    appId: '1:525884237680:ios:0afa7848a6e39f03fb11b5',
    messagingSenderId: '525884237680',
    projectId: 'tuankiet-27c37',
    storageBucket: 'tuankiet-27c37.appspot.com',
    iosBundleId: 'com.example.shopsmartAdminAr.RunnerTests',
  );
}
